// <auto-generated />
namespace MI138_GroupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetags));
        
        string IMigrationMetadata.Id
        {
            get { return "201905161445384_updatetags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
